# Generated by Django 5.1.2 on 2024-10-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='workig',
            new_name='working',
        ),
    ]
